USE `mgpu_ico_db_15`;
-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-11-18 23:56:04 MSK
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE departament 
    ( 
     department_id     INTEGER  NOT NULL , 
     name              VARCHAR (50)  NOT NULL , 
     code              VARCHAR (50)  NOT NULL , 
     parent_department INTEGER 
    ) 
;

ALTER TABLE departament 
    ADD CONSTRAINT departament_PK PRIMARY KEY ( department_id ) ;

CREATE TABLE employee 
    ( 
     employee_id          INTEGER  NOT NULL , 
     last_name            VARCHAR (50)  NOT NULL , 
     first_name           VARCHAR (50)  NOT NULL , 
     middle_name          VARCHAR (50) , 
     birth_date           DATE  NOT NULL , 
     hire_date            DATE  NOT NULL , 
     current_staffing     INTEGER , 
     is_active            CHAR (1)  NOT NULL , 
     staffing_staffing_id INTEGER  NOT NULL 
    ) 
;

ALTER TABLE employee 
    ADD CONSTRAINT employee_PK PRIMARY KEY ( employee_id ) ;

CREATE TABLE movement 
    ( 
     movement_id          INTEGER  NOT NULL , 
     employee_id          INTEGER  NOT NULL , 
     from_staffing        INTEGER , 
     to_staffing          INTEGER  NOT NULL , 
     movement_date        DATE  NOT NULL , 
     reason               VARCHAR (200) , 
     movement_type        VARCHAR (50)  NOT NULL , 
     staffing_staffing_id INTEGER  NOT NULL 
    ) 
;

ALTER TABLE movement 
    ADD CONSTRAINT movement_PK PRIMARY KEY ( movement_id ) ;

CREATE TABLE position_ref 
    ( 
     position_id          INTEGER  NOT NULL , 
     name                 VARCHAR (100)  NOT NULL , 
     grade                VARCHAR (10)  NOT NULL , 
     staffing_staffing_id INTEGER  NOT NULL 
    ) 
;

ALTER TABLE position_ref 
    ADD CONSTRAINT position_ref_PK PRIMARY KEY ( position_id ) ;

CREATE TABLE staffing 
    ( 
     staffing_id               INTEGER  NOT NULL , 
     rate_count                INTEGER  NOT NULL , 
     departament_department_id INTEGER  NOT NULL 
    ) 
;

ALTER TABLE staffing 
    ADD CONSTRAINT staffing_PK PRIMARY KEY ( staffing_id ) ;

ALTER TABLE employee 
    ADD CONSTRAINT employee_staffing_FK FOREIGN KEY 
    ( 
     staffing_staffing_id
    ) 
    REFERENCES staffing 
    ( 
     staffing_id
    ) 
;

ALTER TABLE movement 
    ADD CONSTRAINT movement_staffing_FK FOREIGN KEY 
    ( 
     staffing_staffing_id
    ) 
    REFERENCES staffing 
    ( 
     staffing_id
    ) 
;

ALTER TABLE position_ref 
    ADD CONSTRAINT position_ref_staffing_FK FOREIGN KEY 
    ( 
     staffing_staffing_id
    ) 
    REFERENCES staffing 
    ( 
     staffing_id
    ) 
;

ALTER TABLE staffing 
    ADD CONSTRAINT staffing_departament_FK FOREIGN KEY 
    ( 
     departament_department_id
    ) 
    REFERENCES departament 
    ( 
     department_id
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             5
-- CREATE INDEX                             0
-- ALTER TABLE                              9
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
